### ISSUE TITLE
backend support for filter & sort

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/mico-serengeti-demo#4]

**Comment by alexbfree** [comment]
This is done right @marten ? Can you outline what functionality is available? What fields can I filter by and what is the exact syntax? Also how to specify sort order...?

**Comment by alexbfree** [comment]
I see we had enumerated some of the filter/sort fields in #2... are all these supported? If not can you add them?

**Comment by marten** [comment]
No not all of them, adding them now.

**Comment by marten** [comment]
Fixed by: https://github.com/zooniverse/mico-serengeti-demo/commit/6da75e3677161e08966c113e1e4e2053b8008bb3

See subjects_controller.rb for the parameters names (just normal URL params), should be pretty clear.

**Comment by alexbfree** [comment]
Great, thanks @marten.

It could also be useful to have things like filter by day/night, simple/complex, single/multi, etc if it's not too much extra work.

Also, can you make it so filters can be combined?

e.g. failed images where species = zebra and daytime ?

**Comment by alexbfree** [comment]
ok looking now

**Comment by marten** [comment]
Filters can be combined. The preset filters used in the report, I'll have a look if it's feasible.

**Comment by alexbfree** [comment]
ok great, thanks. filter by dataset is lower priority, but would be useful. i'll leave this ticket open and move it to "nice to have"

**Comment by alexbfree** [comment]
Also it occurs to me it might be more useful to sort by consensus view of how many animals in image, rather than mico's count of how many regions.... or we could support both. again, nice to have but not essential.

**Comment by alexbfree** [comment]
also what is the support for multi-species images?
`?species=multi` ?
or 
`?species=warthog;otherbird` ?
or 
none of the above?

**Comment by alexbfree** [comment]
Added number of animals, number of species, and site_id filters in #28 

Still leaving this open.

**Comment by alexbfree** [comment]
all done at backend.
